// <auto-generated />
using System;
using Integrador.Dal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Integrador.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240522010351_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Integrador.Dal.Entities.Camion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Conductor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroChasis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroMotor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Camiones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2000,
                            Conductor = "Rossi Leonardo",
                            Dominio = "AAA111",
                            Marca = "Scania",
                            Modelo = "P310",
                            NumeroChasis = "12345645",
                            NumeroMotor = "9685741"
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2024,
                            Conductor = "Martinez Carlos",
                            Dominio = "AA1251BC",
                            Marca = "Scania",
                            Modelo = "P420",
                            NumeroChasis = "9124584",
                            NumeroMotor = "987452"
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2005,
                            Conductor = "German Rios",
                            Dominio = "BBB123",
                            Marca = "Ford",
                            Modelo = "F7000",
                            NumeroChasis = "963258",
                            NumeroMotor = "753159"
                        });
                });

            modelBuilder.Entity("Integrador.Dal.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Integrador.Dal.Entities.Viaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CiudadDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CiudadOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLLegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCamion")
                        .HasColumnType("int");

                    b.Property<decimal>("kilometraje")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("IdCamion");

                    b.ToTable("Viajes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CiudadDestino = "Buenos Aires",
                            CiudadOrigen = "Corrientes",
                            FechaLLegada = new DateTime(2024, 10, 10, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2024, 10, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCamion = 1,
                            kilometraje = 800m
                        },
                        new
                        {
                            Id = 2,
                            CiudadDestino = "Mendoza",
                            CiudadOrigen = "Buenos Aires",
                            FechaLLegada = new DateTime(2023, 9, 16, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2023, 9, 15, 9, 35, 0, 0, DateTimeKind.Unspecified),
                            IdCamion = 2,
                            kilometraje = 1050m
                        },
                        new
                        {
                            Id = 3,
                            CiudadDestino = "Buenos Aires",
                            CiudadOrigen = "Salta",
                            FechaLLegada = new DateTime(2021, 2, 4, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaSalida = new DateTime(2021, 2, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCamion = 3,
                            kilometraje = 1500m
                        });
                });

            modelBuilder.Entity("Integrador.Dal.Entities.Viaje", b =>
                {
                    b.HasOne("Integrador.Dal.Entities.Camion", "Camion")
                        .WithMany("Viajes")
                        .HasForeignKey("IdCamion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camion");
                });

            modelBuilder.Entity("Integrador.Dal.Entities.Camion", b =>
                {
                    b.Navigation("Viajes");
                });
#pragma warning restore 612, 618
        }
    }
}
